In [81]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import sklearn
from sklearn.model_selection import train_test_split, StratifiedKFold
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score, f1_score
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC, LinearSVC

In [82]:
data = pd.read_csv('train.csv')
print(data.shape)
print(data_test.isnull().sum().sum())
data.head()

(7352, 563)
0


tBodyAcc-mean()-X  tBodyAcc-mean()-Y  tBodyAcc-mean()-Z  tBodyAcc-std()-X  \
0           0.288585          -0.020294          -0.132905         -0.995279   
1           0.278419          -0.016411          -0.123520         -0.998245   
2           0.279653          -0.019467          -0.113462         -0.995380   
3           0.279174          -0.026201          -0.123283         -0.996091   
4           0.276629          -0.016570          -0.115362         -0.998139   

   tBodyAcc-std()-Y  tBodyAcc-std()-Z  tBodyAcc-mad()-X  tBodyAcc-mad()-Y  \
0         -0.983111         -0.913526         -0.995112         -0.983185   
1         -0.975300         -0.960322         -0.998807         -0.974914   
2         -0.967187         -0.978944         -0.996520         -0.963668   
3         -0.983403         -0.990675         -0.997099         -0.982750   
4         -0.980817         -0.990482         -0.998321         -0.979672   

   tBodyAcc-mad()-Z  tBodyAcc-max()-X  ...  fBodyBodyGyroJerkMag-kurtosis()  \
0         -0.923527         -0.934724  ...                        -0.710304   
1         -0.957686         -0.943068  ...                        -0.861499   
2         -0.977469         -0.938692  ...                        -0.760104   
3         -0.989302         -0.938692  ...                        -0.482845   
4         -0.990441         -0.942469  ...                        -0.699205   

   angle(tBodyAccMean,gravity)  angle(tBodyAccJerkMean),gravityMean)  \
0                    -0.112754                              0.030400   
1                     0.053477                             -0.007435   
2                    -0.118559                              0.177899   
3                    -0.036788                             -0.012892   
4                     0.123320                              0.122542   

   angle(tBodyGyroMean,gravityMean)  angle(tBodyGyroJerkMean,gravityMean)  \
0                         -0.464761                             -0.018446   
1                         -0.732626                              0.703511   
2                          0.100699                              0.808529   
3                          0.640011                             -0.485366   
4                          0.693578                             -0.615971   

   angle(X,gravityMean)  angle(Y,gravityMean)  angle(Z,gravityMean)  subject  \
0             -0.841247              0.179941             -0.058627        1   
1             -0.844788              0.180289             -0.054317        1   
2             -0.848933              0.180637             -0.049118        1   
3             -0.848649              0.181935             -0.047663        1   
4             -0.847865              0.185151             -0.043892        1   

   Activity  
0  STANDING  
1  STANDING  
2  STANDING  
3  STANDING  
4  STANDING  

[5 rows x 563 columns]

In [83]:
data_test = pd.read_csv('test.csv')
print(data_test.shape)
print(data_test.isnull().sum().sum())
data_test.head()

(2947, 563)
0


tBodyAcc-mean()-X  tBodyAcc-mean()-Y  tBodyAcc-mean()-Z  tBodyAcc-std()-X  \
0           0.257178          -0.023285          -0.014654         -0.938404   
1           0.286027          -0.013163          -0.119083         -0.975415   
2           0.275485          -0.026050          -0.118152         -0.993819   
3           0.270298          -0.032614          -0.117520         -0.994743   
4           0.274833          -0.027848          -0.129527         -0.993852   

   tBodyAcc-std()-Y  tBodyAcc-std()-Z  tBodyAcc-mad()-X  tBodyAcc-mad()-Y  \
0         -0.920091         -0.667683         -0.952501         -0.925249   
1         -0.967458         -0.944958         -0.986799         -0.968401   
2         -0.969926         -0.962748         -0.994403         -0.970735   
3         -0.973268         -0.967091         -0.995274         -0.974471   
4         -0.967445         -0.978295         -0.994111         -0.965953   

   tBodyAcc-mad()-Z  tBodyAcc-max()-X  ...  fBodyBodyGyroJerkMag-kurtosis()  \
0         -0.674302         -0.894088  ...                        -0.705974   
1         -0.945823         -0.894088  ...                        -0.594944   
2         -0.963483         -0.939260  ...                        -0.640736   
3         -0.968897         -0.938610  ...                        -0.736124   
4         -0.977346         -0.938610  ...                        -0.846595   

   angle(tBodyAccMean,gravity)  angle(tBodyAccJerkMean),gravityMean)  \
0                     0.006462                              0.162920   
1                    -0.083495                              0.017500   
2                    -0.034956                              0.202302   
3                    -0.017067                              0.154438   
4                    -0.002223                             -0.040046   

   angle(tBodyGyroMean,gravityMean)  angle(tBodyGyroJerkMean,gravityMean)  \
0                         -0.825886                              0.271151   
1                         -0.434375                              0.920593   
2                          0.064103                              0.145068   
3                          0.340134                              0.296407   
4                          0.736715                             -0.118545   

   angle(X,gravityMean)  angle(Y,gravityMean)  angle(Z,gravityMean)  subject  \
0             -0.720009              0.276801             -0.057978        2   
1             -0.698091              0.281343             -0.083898        2   
2             -0.702771              0.280083             -0.079346        2   
3             -0.698954              0.284114             -0.077108        2   
4             -0.692245              0.290722             -0.073857        2   

   Activity  
0  STANDING  
1  STANDING  
2  STANDING  
3  STANDING  
4  STANDING  

[5 rows x 563 columns]

In [84]:
X = data.iloc[:,:-1]
y = data.iloc[:,-1]
print(X.shape)
print(y.unique())

(7352, 562)
['STANDING' 'SITTING' 'LAYING' 'WALKING' 'WALKING_DOWNSTAIRS'
 'WALKING_UPSTAIRS']


In [60]:
X.describe()

tBodyAcc-mean()-X  tBodyAcc-mean()-Y  tBodyAcc-mean()-Z  \
count        7352.000000        7352.000000        7352.000000   
mean            0.274488          -0.017695          -0.109141   
std             0.070261           0.040811           0.056635   
min            -1.000000          -1.000000          -1.000000   
25%             0.262975          -0.024863          -0.120993   
50%             0.277193          -0.017219          -0.108676   
75%             0.288461          -0.010783          -0.097794   
max             1.000000           1.000000           1.000000   

       tBodyAcc-std()-X  tBodyAcc-std()-Y  tBodyAcc-std()-Z  tBodyAcc-mad()-X  \
count       7352.000000       7352.000000       7352.000000       7352.000000   
mean          -0.605438         -0.510938         -0.604754         -0.630512   
std            0.448734          0.502645          0.418687          0.424073   
min           -1.000000         -0.999873         -1.000000         -1.000000   
25%           -0.992754         -0.978129         -0.980233         -0.993591   
50%           -0.946196         -0.851897         -0.859365         -0.950709   
75%           -0.242813         -0.034231         -0.262415         -0.292680   
max            1.000000          0.916238          1.000000          1.000000   

       tBodyAcc-mad()-Y  tBodyAcc-mad()-Z  tBodyAcc-max()-X  ...  \
count       7352.000000       7352.000000       7352.000000  ...   
mean          -0.526907         -0.606150         -0.468604  ...   
std            0.485942          0.414122          0.544547  ...   
min           -1.000000         -1.000000         -1.000000  ...   
25%           -0.978162         -0.980251         -0.936219  ...   
50%           -0.857328         -0.857143         -0.881637  ...   
75%           -0.066701         -0.265671         -0.017129  ...   
max            0.967664          1.000000          1.000000  ...   

       fBodyBodyGyroJerkMag-skewness()  fBodyBodyGyroJerkMag-kurtosis()  \
count                      7352.000000                      7352.000000   
mean                         -0.307009                        -0.625294   
std                           0.321011                         0.307584   
min                          -0.995357                        -0.999765   
25%                          -0.542602                        -0.845573   
50%                          -0.343685                        -0.711692   
75%                          -0.126979                        -0.503878   
max                           0.989538                         0.956845   

       angle(tBodyAccMean,gravity)  angle(tBodyAccJerkMean),gravityMean)  \
count                  7352.000000                           7352.000000   
mean                      0.008684                              0.002186   
std                       0.336787                              0.448306   
min                      -0.976580                             -1.000000   
25%                      -0.121527                             -0.289549   
50%                       0.009509                              0.008943   
75%                       0.150865                              0.292861   
max                       1.000000                              1.000000   

       angle(tBodyGyroMean,gravityMean)  angle(tBodyGyroJerkMean,gravityMean)  \
count                       7352.000000                           7352.000000   
mean                           0.008726                             -0.005981   
std                            0.608303                              0.477975   
min                           -1.000000                             -1.000000   
25%                           -0.482273                             -0.376341   
50%                            0.008735                             -0.000368   
75%                            0.506187                              0.359368   
max                            0.998702                     

In [61]:
y.groupby(by=y).count()

Activity
LAYING                1407
SITTING               1286
STANDING              1374
WALKING               1226
WALKING_DOWNSTAIRS     986
WALKING_UPSTAIRS      1073
Name: Activity, dtype: int64

In [53]:
kf = StratifiedKFold(n_splits=3, shuffle=True, random_state=42)
indexes = kf.split(X, y)
acc = []
for k in [1, 5, 10]:
    for m in ['euclidean', 'manhattan']:
        indexes = kf.split(X, y)
        acc_tmp = []
        fin_conf_mat = np.zeros((len(np.unique(y)),len(np.unique(y))))
        for train_index, test_index in indexes:
            classifier = KNeighborsClassifier(n_neighbors=k, metric=m)
            classifier.fit(X.iloc[train_index,:], y.iloc[train_index])
            y_pred = classifier.predict(X.iloc[test_index,:])
            acc_tmp.append(accuracy_score(y.iloc[test_index], y_pred))
            fin_conf_mat += confusion_matrix(y.iloc[test_index], y_pred)
        print('za parametre k=', k, ' i m=', m, ' tacnost je: ', np.mean(acc_tmp), ' a mat. konf. je:')
        print(fin_conf_mat)
        acc.append(np.mean(acc_tmp))
print('najbolja tacnost je u iteraciji broj: ', np.argmax(acc))

za parametre k= 1  i m= euclidean  tacnost je:  0.9747007607612609  a mat. konf. je:
[[1.405e+03 2.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00]
 [0.000e+00 1.184e+03 1.010e+02 0.000e+00 0.000e+00 1.000e+00]
 [0.000e+00 7.500e+01 1.299e+03 0.000e+00 0.000e+00 0.000e+00]
 [0.000e+00 0.000e+00 0.000e+00 1.224e+03 0.000e+00 2.000e+00]
 [0.000e+00 0.000e+00 0.000e+00 3.000e+00 9.810e+02 2.000e+00]
 [0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00 1.073e+03]]
za parametre k= 1  i m= manhattan  tacnost je:  0.9851740092201711  a mat. konf. je:
[[1.405e+03 1.000e+00 1.000e+00 0.000e+00 0.000e+00 0.000e+00]
 [0.000e+00 1.218e+03 6.700e+01 0.000e+00 0.000e+00 1.000e+00]
 [0.000e+00 3.500e+01 1.339e+03 0.000e+00 0.000e+00 0.000e+00]
 [0.000e+00 0.000e+00 0.000e+00 1.225e+03 0.000e+00 1.000e+00]
 [0.000e+00 0.000e+00 0.000e+00 2.000e+00 9.840e+02 0.000e+00]
 [0.000e+00 0.000e+00 0.000e+00 1.000e+00 0.000e+00 1.072e+03]]
za parametre k= 5  i m= euclidean  tacnost je:  0.9649072293135941  a ma

In [85]:
classifier = KNeighborsClassifier(n_neighbors=1, metric='manhattan')
classifier.fit(X, y)
y_pred = classifier.predict(data_test.iloc[:,:-1])
conf_mat = confusion_matrix(data_test.iloc[:,-1], y_pred)
print(conf_mat)
print('procenat pogodjenih uzoraka: ', accuracy_score(data_test.iloc[:,-1], y_pred))
print('preciznost mikro: ', precision_score(data_test.iloc[:,-1], y_pred, average='micro'))
print('preciznost makro: ', precision_score(data_test.iloc[:,-1], y_pred, average='macro'))
print('osetljivost mikro: ', recall_score(data_test.iloc[:,-1], y_pred, average='micro'))
print('osetljivost makro: ', recall_score(data_test.iloc[:,-1], y_pred, average='macro'))
print('f mera mikro: ', f1_score(data_test.iloc[:,-1], y_pred, average='micro'))
print('f mera makro: ', f1_score(data_test.iloc[:,-1], y_pred, average='macro'))


[[529   3   5   0   0   0]
 [  3 370 118   0   0   0]
 [  0  46 486   0   0   0]
 [  0   0   0 467  13  16]
 [  0   0   0  46 340  34]
 [  0   0   0  38  11 422]]
procenat pogodjenih uzoraka:  0.8870037326094333
preciznost mikro:  0.8870037326094333
preciznost makro:  0.8918548319065532
osetljivost mikro:  0.8870037326094333
osetljivost makro:  0.8832037512569242
f mera mikro:  0.8870037326094333
f mera makro:  0.8848694280587229


In [65]:
kf = StratifiedKFold(n_splits=3, shuffle=True, random_state=42)
indexes = kf.split(X, y)
acc = []
for c in [1, 10, 100]:
    for F in ['linear', 'rbf']:
        for mc in ['ovo', 'ovr']:
            indexes = kf.split(X, y)
            acc_tmp = []
            fin_conf_mat = np.zeros((len(np.unique(y)),len(np.unique(y))))
            for train_index, test_index in indexes:
                classifier = SVC(C=c, kernel=F, decision_function_shape=mc)
                classifier.fit(X.iloc[train_index,:], y.iloc[train_index])
                y_pred = classifier.predict(X.iloc[test_index,:])
                acc_tmp.append(accuracy_score(y.iloc[test_index], y_pred))
                fin_conf_mat += confusion_matrix(y.iloc[test_index], y_pred)
            print('za parametre C=', c, ', kernel=', F, ' i pristup ', mc, ' tacnost je: ', np.mean(acc_tmp),
                  ' a mat. konf. je:')
            print(fin_conf_mat)
            acc.append(np.mean(acc_tmp))
print('najbolja tacnost je u iteraciji broj: ', np.argmax(acc))

za parametre C= 1 , kernel= linear  i pristup  ovo  tacnost je:  0.9861260571139921  a mat. konf. je:
[[1.407e+03 0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00]
 [1.000e+00 1.241e+03 4.300e+01 0.000e+00 0.000e+00 1.000e+00]
 [0.000e+00 5.400e+01 1.320e+03 0.000e+00 0.000e+00 0.000e+00]
 [0.000e+00 0.000e+00 0.000e+00 1.225e+03 0.000e+00 1.000e+00]
 [0.000e+00 0.000e+00 0.000e+00 1.000e+00 9.840e+02 1.000e+00]
 [0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00 1.073e+03]]
za parametre C= 1 , kernel= linear  i pristup  ovr  tacnost je:  0.9861260571139921  a mat. konf. je:
[[1.407e+03 0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00]
 [1.000e+00 1.241e+03 4.300e+01 0.000e+00 0.000e+00 1.000e+00]
 [0.000e+00 5.400e+01 1.320e+03 0.000e+00 0.000e+00 0.000e+00]
 [0.000e+00 0.000e+00 0.000e+00 1.225e+03 0.000e+00 1.000e+00]
 [0.000e+00 0.000e+00 0.000e+00 1.000e+00 9.840e+02 1.000e+00]
 [0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00 1.073e+03]]
za parametre C= 1 , kernel= rbf  i pri

In [86]:
classifier = SVC(C=100, kernel='rbf', decision_function_shape='ovr')
classifier.fit(X, y)
y_pred = classifier.predict(data_test.iloc[:,:-1])
conf_mat = confusion_matrix(data_test.iloc[:,-1], y_pred)
print(conf_mat)
print('procenat pogodjenih uzoraka: ', accuracy_score(data_test.iloc[:,-1], y_pred))
print('preciznost mikro: ', precision_score(data_test.iloc[:,-1], y_pred, average='micro'))
print('preciznost makro: ', precision_score(data_test.iloc[:,-1], y_pred, average='macro'))
print('osetljivost mikro: ', recall_score(data_test.iloc[:,-1], y_pred, average='micro'))
print('osetljivost makro: ', recall_score(data_test.iloc[:,-1], y_pred, average='macro'))
print('f mera mikro: ', f1_score(data_test.iloc[:,-1], y_pred, average='micro'))
print('f mera makro: ', f1_score(data_test.iloc[:,-1], y_pred, average='macro'))

[[537   0   0   0   0   0]
 [  0 419  71   0   0   1]
 [  0  16 516   0   0   0]
 [  0   0   0 493   3   0]
 [  0   0   0  13 391  16]
 [  0   0   0  24   7 440]]
procenat pogodjenih uzoraka:  0.9487614523243977
preciznost mikro:  0.9487614523243977
preciznost makro:  0.9517193810093166
osetljivost mikro:  0.9487614523243977
osetljivost makro:  0.9470619808195998
f mera mikro:  0.9487614523243977
f mera makro:  0.9481676792569664


In [87]:
X = data.iloc[:,:-2]
classifier = KNeighborsClassifier(n_neighbors=1, metric='manhattan')
classifier.fit(X, y)
y_pred = classifier.predict(data_test.iloc[:,:-2])
conf_mat = confusion_matrix(data_test.iloc[:,-1], y_pred)
print(conf_mat)
print('procenat pogodjenih uzoraka: ', accuracy_score(data_test.iloc[:,-1], y_pred))
print('preciznost mikro: ', precision_score(data_test.iloc[:,-1], y_pred, average='micro'))
print('preciznost makro: ', precision_score(data_test.iloc[:,-1], y_pred, average='macro'))
print('osetljivost mikro: ', recall_score(data_test.iloc[:,-1], y_pred, average='micro'))
print('osetljivost makro: ', recall_score(data_test.iloc[:,-1], y_pred, average='macro'))
print('f mera mikro: ', f1_score(data_test.iloc[:,-1], y_pred, average='micro'))
print('f mera makro: ', f1_score(data_test.iloc[:,-1], y_pred, average='macro'))

[[535   2   0   0   0   0]
 [  1 383 106   0   0   1]
 [  0  62 470   0   0   0]
 [  0   0   0 475  10  11]
 [  0   0   0  33 332  55]
 [  0   0   0  39   8 424]]
procenat pogodjenih uzoraka:  0.8887003732609433
preciznost mikro:  0.8887003732609433
preciznost makro:  0.8919029961476186
osetljivost mikro:  0.8887003732609433
osetljivost makro:  0.8846874633420123
f mera mikro:  0.8887003732609433
f mera makro:  0.886146559687511


In [88]:
classifier = SVC(C=100, kernel='rbf', decision_function_shape='ovr')
classifier.fit(X, y)
y_pred = classifier.predict(data_test.iloc[:,:-2])
conf_mat = confusion_matrix(data_test.iloc[:,-1], y_pred)
print(conf_mat)
print('procenat pogodjenih uzoraka: ', accuracy_score(data_test.iloc[:,-1], y_pred))
print('preciznost mikro: ', precision_score(data_test.iloc[:,-1], y_pred, average='micro'))
print('preciznost makro: ', precision_score(data_test.iloc[:,-1], y_pred, average='macro'))
print('osetljivost mikro: ', recall_score(data_test.iloc[:,-1], y_pred, average='micro'))
print('osetljivost makro: ', recall_score(data_test.iloc[:,-1], y_pred, average='macro'))
print('f mera mikro: ', f1_score(data_test.iloc[:,-1], y_pred, average='micro'))
print('f mera makro: ', f1_score(data_test.iloc[:,-1], y_pred, average='macro'))

[[537   0   0   0   0   0]
 [  0 443  46   0   0   2]
 [  0   8 524   0   0   0]
 [  0   0   0 489   3   4]
 [  0   0   0   4 398  18]
 [  0   0   0  16   1 454]]
procenat pogodjenih uzoraka:  0.9653885307091958
preciznost mikro:  0.9653885307091958
preciznost makro:  0.9670179502983881
osetljivost mikro:  0.9653885307091958
osetljivost makro:  0.9641025763358061
f mera mikro:  0.9653885307091958
f mera makro:  0.964975164695753
